version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: buber-dinner-sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Compl3taPassw0rd!"
    volumes:
      - ~/docker-volumes/bubderdinner/db:/var/opt/mssql
