### Setup
@BuberDinner.Api_HostAddress = https://localhost:5003
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlci5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IkFuZHJldyIsImZhbWlseV9uYW1lIjoiV2hpdGUiLCJuYmYiOjE3MjU3MDQ3MDksImV4cCI6MTcyNTcwODMwOSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.xaTzjnYLTbDSHrssDYwA3FHwJcvlB8iHLSt0qh6WrE0

### List dinners
GET {{BuberDinner.Api_HostAddress}}/dinners
Content-Type: application/json
Authorization: Bearer {{token}}
